//#define NORTHEAST "02"
#define NORTHWEST "02"
//#define NORTH "50"
//#define SOUTH "46"
#define EAST "04"
//#define WEST "47"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
