//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "50"
#define SOUTH "08"
#define EAST "12"
#define WEST "51"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
