#define NORTHEAST "28"
//#define NORTHWEST "42"
//#define NORTH "50"
#define SOUTH "30"
//#define EAST "34"
//#define WEST "21"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
