//#define NORTHEAST "02"
//#define NORTHWEST "42"
#define NORTH "29"
//#define SOUTH "46"
//#define EAST "23"
//#define WEST "21"
//#define SOUTHEAST "41"
#define SOUTHWEST "31"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
