//#define NORTHEAST "02"
//#define NORTHWEST "42"
#define NORTH "37"
#define SOUTH "35"
//#define EAST "23"
//#define WEST "21"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
