//#define NORTHEAST "02"
//#define NORTHWEST "42"
#define NORTH "44"
#define SOUTH "43"
#define EAST "42"
#define WEST "40"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
