#define NORTHEAST "50"
//#define NORTHWEST "42"
//#define NORTH "35"
#define SOUTH "42"
//#define EAST "23"
//#define WEST "21"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
