//  coded by Triskadekta
#include "../munitio.h"
#include <std.h>

inherit ROOM;
void create() {
	::create();
	
	set_property("light", 1);	
	set_property("indoors", 0);
	set("short", "The Streets of Munitio");
	set("long", "This is the eastern edge of the forge area. The streets are not quite as muddy here, probably because of the intense heat generated by all the forges. Several blacksmiths walk by you, carrying blanks to be forged. To the north are several small houses, and to the west several forges can be seen.");
set_items( (["houses": "Even from a distance, you can tell you wouldn't want to live in them.",
"forges": "Blacksmiths need forges to forge things, or so you've been told.",
"blanks": "You use one or two ingots to make them. You then use them to make weapons or armour." ]) );
	add_exit(ROOMS+"city1", "south");
	add_exit(ROOMS+"city8", "north");
	add_exit(ROOMS+"city5", "west");
}


void reset() {
	::reset();
if(!present("guard")){
	new(MON+"cityguard.c")->move(this_object());
}

if(!present("citizen")){
	new(MON+"citizen.c")->move(this_object());
	new(MON+"citizen.c")->move(this_object());
	new(MON+"citizen.c")->move(this_object());
}
}
