//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "50"
//#define SOUTH "46"
//#define EAST "48"
//#define WEST "47"
#define SOUTHEAST "03"
#define SOUTHWEST "01"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
