//#define NORTHEAST "02"
//#define NORTHWEST "02"
#define NORTH "06"
#define SOUTH "04"
//#define EAST "04"
//#define WEST "47"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
