//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "50"
//#define SOUTH "46"
//#define EAST "48"
#define WEST "08"
#define SOUTHEAST "06"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
