//#define NORTHEAST "02"
//#define NORTHWEST "42"
#define NORTH "11"
#define SOUTH "10"
#define EAST "07"
#define WEST "09"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
