//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "50"
#define SOUTH "14"
//#define EAST "48"
#define WEST "12"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
