//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "50"
#define SOUTH "26"
//#define EAST "23"
#define WEST "24"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
