//#define NORTHEAST "02"
#define NORTHWEST "26"
//#define NORTH "50"
#define SOUTH "28"
//#define EAST "23"
//#define WEST "21"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
