//#define NORTHEAST "02"
//#define NORTHWEST "42"
#define NORTH "46"
#define SOUTH "48"
#define EAST "45"
#define WEST "39"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
