//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "35"
//#define SOUTH "33"
//#define EAST "23"
#define WEST "45"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base2.c"
