//#define NORTHEAST "02"
//#define NORTHWEST "42"
#define NORTH "42"
//#define SOUTH "33"
//#define EAST "23"
//#define WEST "21"
#define SOUTHEAST "49"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
