//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "35"
//#define SOUTH "33"
#define EAST "11"
//#define WEST "21"
//#define SOUTHEAST "41"
//#define SOUTHWEST "46"
//#define UP "45"
//#define DOWN "45"
#include "base.c"
