//#define NORTHEAST "30"
//#define NORTHWEST "42"
//#define NORTH "40"
//#define SOUTH "41"
//#define EAST "38"
#define WEST "43"
#define SOUTHEAST "41"
//#define SOUTHWEST "30"
#include "base_curse.c"
