#define PATH            "/d/areas/descent"
#define ROOMS           PATH+"/rooms/"
#define MON             PATH+"/mon/"
#define OBJ             PATH+"/obj/"
#define WEAP            PATH+"/weapon/"
#define ARMOR           PATH+"/armor/"
