//#define NORTHEAST "03"
//#define NORTHWEST "03"
//#define NORTH "08"
#define SOUTH "07"
#define EAST "13"
#define WEST "09"
//#define SOUTHEAST "04"
//#define SOUTHWEST "02"
//#define UP "entry"
#include "base.c"
