//#define NORTHEAST "03"
//#define NORTHWEST "03"
//#define NORTH "08"
#define SOUTH "10"
#define EAST "08"
//#define WEST "08"
//#define SOUTHEAST "04"
//#define SOUTHWEST "02"
//#define UP "entry"
#include "base.c"
