//#define NORTHEAST "03"
//#define NORTHWEST "03"
#define NORTH "13"
#define SOUTH "15"
//#define EAST "13"
//#define WEST "08"
//#define SOUTHEAST "04"
//#define SOUTHWEST "02"
//#define UP "entry"
#include "base.c"
