//#define NORTHEAST "03"
//#define NORTHWEST "03"
//#define NORTH "15"
//#define SOUTH "16"
#define EAST "18"
#define WEST "16"
//#define SOUTHEAST "04"
//#define SOUTHWEST "02"
//#define UP "entry"
#include "base.c"
