#define NORTHEAST "28"
//#define NORTHWEST "03"
//#define NORTH "15"
#define SOUTH "19"
//#define EAST "18"
#define WEST "17"
//#define SOUTHEAST "04"
//#define SOUTHWEST "02"
//#define UP "entry"
#include "base.c"
