//#define NORTHEAST "02"
//#define NORTHWEST "42"
#define NORTH "06"
//#define SOUTH "46"
//#define EAST "48"
//#define WEST "47"
#define SOUTHEAST "04"
#define SOUTHWEST "02"
//#define UP "45"
//#define DOWN "45"
//#define UP "entry"
#include "base.c"
