//#define NORTHEAST "02"
//#define NORTHWEST "42"
//#define NORTH "50"
//#define SOUTH "46"
//#define EAST "48"
#define WEST "43"
#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "45"
//#define DOWN "45"
//#define UP "entry"
#include "base.c"
