//#define NORTHEAST "46"
//#define NORTHWEST "42"
#define NORTH "05"
#define SOUTH "01"
#define EAST "04"
#define WEST "03"
//#define SOUTHEAST "41"
//#define SOUTHWEST "45"
//#define UP "entry"
#include "base.c"
