<HTML>
<HEAD>
<TITLE>Overworld Map</TITLE>
</HEAD>
<BODY>
<?

  function print_char($printchar){
    switch($printchar){
      case "F":
        print("<font color=\"#336600\">F</font>");
        break;
      case "S":
        print("<font color=\"#999900\">S</font>");
        break;
      case "T":
        print("<font color=\"#FFFFCC\">T</font>");
        break;
      case "P":
        print("<font color=\"#66FF33\">P</font>");
        break;
      case "H":
        print("<font color=\"#9900FF\">H</font>");
        break;
      case "W":
        print("<font color=\"#3333CC\">W</font>");
        break;
      case "J":
        print("<font color=\"#FF3300\">J</font>");
        break;
      case "\n":
        print("<BR>");
        break;
      default:
        break;
    }
  }

  $filename="../d/damned/data/world_terrain.db";

  if(!($myfile = fopen($filename, "r"))){
    print("Error: Couldn't open world terrain file.\n");
    exit;
  }

  while(!feof($myfile)){
    $mychar=fgetc($myfile);
    print_char($mychar); 
  }

  print("<P><P>Generated by ");
  print("<A href="mailto:david@zakar.com">Tailwind</A>'s script at: ");
  print(date("h:i A l F dS, Y"));
  print(".");

?>

</BODY>
</HTML>