<HTML>
<HEAD>
<TITLE>Overworld Map</TITLE>
</HEAD>
<BODY>
<font face="courier new">
<font face="courier new">
<?

  $lastchar=":";

  function print_char($printchar, $lastchar){
    if($printchar == $lastchar){
      print($lastchar);
    }
    else{
      switch($printchar){
        case "F":
          print("</font><font color=\"#336600\">F");
          break;
        case "S":
          print("</font><font color=\"#999900\">S");
          break;
        case "T":
          print("</font><font color=\"#FFFFCC\">T");
          break;
        case "P":
          print("</font><font color=\"#66FF33\">P");
          break;
        case "H":
          print("</font><font color=\"#9900FF\">H");
          break;
        case "W":
          print("</font><font color=\"#3333CC\">W");
          break;
        case "J":
          print("</font><font color=\"#FF3300\">J");
          break;
        case "D":
          print("</font><font color=\"#FF3300\">D");
          break;
        case "C":
          print("</font><font color=\"#FF3300\">C");
          break;
        case "M":
          print("</font><font color=\"#FF00FF\">M");
          break;
        case "\n":
          print("<BR>");
          break;
        default:
          break;
      }
    }
  }

  $filename="../d/damned/data/world_terrain.db";

  if(!($myfile = fopen($filename, "r"))){
    print("Error: Couldn't open world terrain file.\n");
    exit;
  }

  while(!feof($myfile)){
    $mychar=fgetc($myfile);
    print_char($mychar, $prevchar);
    if(!($mychar=="\n" || $mychar==":")) $prevchar=$mychar; 
  }

  print("<P><P></font>Generated by ");
  print("<A href=\"mailto:david@zakar.com\">Tailwind</A>'s script at: ");
  print(date("h:i A l F dS, Y"));
  print(".");

  fclose($myfile);

?>
</font>
</font>
</BODY>
</HTML>